# -*- coding: utf-8 -*-
"""Healthcare_data_stroke.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmCKccWkKKByyyfS4Pv0HWk1_KcVgXop
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

data=pd.read_csv('healthcare-dataset-stroke-data.csv')
data.head()

data.shape

data.info()

data.isnull().sum()

"""REPLACE NULL VALUES WITH MEAN"""

mean_bmi=data['bmi'].mean()
data['bmi'].fillna(mean_bmi,inplace=True)

data.duplicated().sum()

data.isnull().sum()

"""UNIVARIATE ANALYSIS"""

sns.histplot(data['age'])
plt.title('Age Distribution')

sns.histplot(data['bmi'])
plt.title('BMI Distribution')

sns.countplot(data['gender'])
plt.title('Gender Distribution')

sns.countplot(data['smoking_status'])
plt.title('Smoking Status Distribution')

sns.countplot(data['work_type'])
plt.title('Work Type Distribution')

"""BIVARIATE ANALYSIS"""

sns.countplot(x='gender',hue='stroke',data=data)
plt.title('Gender vs Stroke_Distribution')

sns.boxplot(x='stroke', y='age', data=data)
plt.title("Age and Stroke Relationship")

sns.countplot(x='smoking_status', hue='stroke', data=data)
plt.title("Smoking Status vs Stroke")

"""CORRELATION HEATMAP"""

plt.figure(figsize=(8,6))
sns.heatmap(data.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")